title: Xihong Zhou
email: g863003a@mails.cc.ehime-u.ac.jp
github_username: XihongZhou
viewsourceroot: https://github.com/xihongzhou/xihongzhou.github.io/blob/gh-pages/
newsourceroot: https://github.com/xihongzhou/xihongzhou.github.io/new/gh-pages

# duoshuo_shortname: xihongzhou
duoshuo_url: "http://xihongzhou.duoshuo.com"
# disqus_shortname: xihongzhou
# Build settings
markdown: kramdown

