title: Xihong Zhou
email: g863003a@mails.cc.ehime-u.ac.jp
github_username: XihongZhou
viewsourceroot: https://github.com/xihongzhou/xihongzhou.github.io/blob/gh-pages/
newsourceroot: https://github.com/xihongzhou/xihongzhou.github.io/new/gh-pages

# Build settings
markdown: kramdown

port: 4001
